## BUILD STAGE
FROM maven AS build

WORKDIR /app
COPY . .

RUN mvn install

## FINAL STAGE
FROM openjdk:jre

WORKDIR /app
# Copy jar from build
COPY --from=build /app/target/*-fat.jar .

ENV PORT=80

# Launch the verticle
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar *-fat.jar"]
